Repository seb-oss/ng-components, pull requests merged in 2020-07, with the labels that each got.

#334 feat(tooltip): add tooltip
  lib/src/public_api.ts
  lib/src/tooltip/index.ts
  lib/src/tooltip/tooltip-content/tooltip-content.component.html
  lib/src/tooltip/tooltip-content/tooltip-content.component.scss
  lib/src/tooltip/tooltip-content/tooltip-content.component.spec.ts
  lib/src/tooltip/tooltip-content/tooltip-content.component.ts
  lib/src/tooltip/tooltip.component.html
  lib/src/tooltip/tooltip.component.scss
  lib/src/tooltip/tooltip.component.spec.ts
  lib/src/tooltip/tooltip.component.ts
  lib/src/tooltip/tooltip.directive.spec.ts
  lib/src/tooltip/tooltip.directive.ts
  lib/src/tooltip/tooltip.module.ts
  package-lock.json
  package.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/components/example-page/api-list/api-list.component.ts
  projects/ng-components-docs/src/app/components/menu/side-menu.component.html
  projects/ng-components-docs/src/app/components/menu/side-menu.component.scss
  projects/ng-components-docs/src/app/examples/components/tooltip/examples/tooltip/tooltip.component.html
  projects/ng-components-docs/src/app/examples/components/tooltip/examples/tooltip/tooltip.component.ts
  projects/ng-components-docs/src/app/examples/components/tooltip/tooltip.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: 🔨 Enhancement

#293 feat(table): table
  lib/src/__utils/safe-html.pipe.ts
  lib/src/table/index.ts
  lib/src/table/table-body/table-body.component.html
  lib/src/table/table-body/table-body.component.ts
  lib/src/table/table-header/table-header.component.html
  lib/src/table/table-header/table-header.component.ts
  lib/src/table/table-td/table-td.component.html
  lib/src/table/table-td/table-td.component.ts
  lib/src/table/table-th/table-th.component.html
  lib/src/table/table-th/table-th.component.ts
  lib/src/table/table.component.html
  lib/src/table/table.component.scss
  lib/src/table/table.component.spec.ts
  lib/src/table/table.component.ts
  lib/src/table/table.models.ts
  lib/src/table/table.module.ts
  lib/src/table/table.service.spec.ts
  lib/src/table/table.service.ts
  lib/src/utils.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/table/examples/full-table-example.component.html
  projects/ng-components-docs/src/app/examples/components/table/examples/full-table-example.component.ts
  projects/ng-components-docs/src/app/examples/components/table/table-examples.component.html
  projects/ng-components-docs/src/app/examples/components/table/table-examples.component.ts
  projects/ng-components-docs/src/app/examples/components/table/table.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: 🔨 Enhancement

#351 Feature/loader
  lib/src/loader/index.ts
  lib/src/loader/loader.component.html
  lib/src/loader/loader.component.scss
  lib/src/loader/loader.component.spec.ts
  lib/src/loader/loader.component.ts
  lib/src/loader/loader.module.ts
  lib/src/loader/loader.pipe.ts
  package-lock.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/loader/loader.component.html
  projects/ng-components-docs/src/app/examples/components/loader/loader.component.ts
  projects/ng-components-docs/src/app/examples/components/loader/loader.module.ts
Labels: 🔨 Enhancement

#316 Feature/checkbox
  README.md
  lib/src/checkBox/checkBox.component.html
  lib/src/checkBox/checkBox.component.scss
  lib/src/checkBox/checkBox.component.spec.ts
  lib/src/checkBox/checkBox.component.ts
  lib/src/checkBox/checkBox.module.ts
  lib/src/checkBox/index.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/checkBox/checkBox.component.html
  projects/ng-components-docs/src/app/examples/components/checkBox/checkBox.component.scss
  projects/ng-components-docs/src/app/examples/components/checkBox/checkBox.component.spec.ts
  projects/ng-components-docs/src/app/examples/components/checkBox/checkBox.component.ts
  projects/ng-components-docs/src/app/examples/components/checkBox/checkBox.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: 🔨 Enhancement

#343 feat(stepper): stepper component
  lib/src/stepper/index.ts
  lib/src/stepper/stepper.component.html
  lib/src/stepper/stepper.component.scss
  lib/src/stepper/stepper.component.spec.ts
  lib/src/stepper/stepper.component.ts
  lib/src/stepper/stepper.module.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/stepper/stepper-examples.component.html
  projects/ng-components-docs/src/app/examples/components/stepper/stepper-examples.component.ts
  projects/ng-components-docs/src/app/examples/components/stepper/stepper.module.ts
Labels: 🔨 Enhancement

#363 docs(api-list-component): fix documentation issue
  lib/src/chip/chip.component.html
  lib/src/chip/chip.component.ts
  lib/src/tooltip/tooltip.component.ts
  lib/src/tooltip/tooltip.directive.ts
  package-lock.json
  package.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/components/example-page/api-list/api-list.component.html
  projects/ng-components-docs/src/app/components/example-page/api-list/api-list.component.ts
Labels: 🐛 Bug, 📚 Documentation, 📦 Dependencies

#349 Feature/timer
  lib/src/timer/index.ts
  lib/src/timer/timer.component.html
  lib/src/timer/timer.component.spec.ts
  lib/src/timer/timer.component.ts
  lib/src/timer/timer.module.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/timer/timer.component.html
  projects/ng-components-docs/src/app/examples/components/timer/timer.component.ts
  projects/ng-components-docs/src/app/examples/components/timer/timer.module.ts
Labels: 🔨 Enhancement

#274 feat(notification): new notification component
  lib/src/notification/index.ts
  lib/src/notification/notification.component.html
  lib/src/notification/notification.component.scss
  lib/src/notification/notification.component.spec.ts
  lib/src/notification/notification.component.ts
  lib/src/notification/notification.module.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/notification/notification.component.html
  projects/ng-components-docs/src/app/examples/components/notification/notification.component.ts
  projects/ng-components-docs/src/app/examples/components/notification/notification.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: 🔨 Enhancement

#372 fix(fix lib build): fix lib build
  angular.json
  lib/ng-package.json
  lib/public_api.ts
  lib/src/accordion/package.json
  lib/src/breadcrumb/package.json
  lib/src/button/package.json
  lib/src/checkBox/package.json
  lib/src/chip/package.json
  lib/src/modal/package.json
  lib/src/notification/notification.component.ts
  lib/src/notification/package.json
  lib/src/pagination/package.json
  lib/src/progressBar/package.json
  lib/src/radio-group/package.json
  lib/src/rating/package.json
  lib/src/slider/package.json
  lib/src/slider/slider.pipes.ts
  lib/src/stepper/package.json
  lib/src/table/package.json
  lib/src/table/table-td/table-td.component.ts
  lib/src/table/table.module.ts
  lib/src/table/table.pipe.ts
  lib/src/table/table.service.ts
  lib/src/table/utils.ts
  lib/src/tabs/package.json
  lib/src/tabs/tabs.component.html
  lib/src/textArea/package.json
  lib/src/textLabel/package.json
  lib/src/textboxGroup/package.json
  lib/src/timeline/package.json
  lib/src/timeline/timeline.component.html
  lib/src/timer/package.json
  lib/src/toggle/package.json
  lib/src/tooltip/package.json
  lib/src/video/package.json
  lib/src/video/video.component.ts
  package.json
Labels: 🐛 Bug

#384 feat: add checkbox, modal, textlabel docs
  package-lock.json
  package.json
  projects/docs/src/app/common/services/api-extract.service.ts
  projects/docs/src/app/docs-wrapper/docs-wrapper.component.scss
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.html
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.html
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.scss
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.component.html
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.module.ts
  projects/ng-components/lib/modal/animation.ts
  projects/ng-components/lib/modal/modal.component.scss
  projects/ng-components/lib/modal/modal.component.ts
  projects/ng-components/lib/textLabel/textLabel.component.ts
Labels: 🐛 Bug, 📚 Documentation, 🔨 Enhancement

#402 Update build-check.yml
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
Labels: 🚀 CI/CD

#390 feat: refactor modal to use toggle instead of viewchild, and extra inputs, fix unit tests
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.html
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.ts
  projects/ng-components/lib/modal/modal.backdrop.ts
  projects/ng-components/lib/modal/modal.component.html
  projects/ng-components/lib/modal/modal.component.spec.ts
  projects/ng-components/lib/modal/modal.component.ts
  projects/ng-components/lib/modal/modal.service.ts
Labels: 🔨 Enhancement

#408 Docs/fix docs styles
  angular.json
  package.json
  projects/docs/src/@types/index.d.ts
  projects/docs/src/app/common/code-snippet/code-snippet.component.scss
  projects/docs/src/app/common/side-menu/side-menu.component.scss
  projects/docs/src/app/common/tech-stack/tech-stack.component.scss
  projects/docs/src/app/docs-wrapper/doc-page/apis/apis.component.scss
  projects/docs/src/app/docs-wrapper/doc-page/apis/apis.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/notes/notes.component.scss
  projects/docs/src/app/docs-wrapper/doc-page/notes/notes.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.html
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.scss
  projects/docs/src/app/docs-wrapper/docs-wrapper.module.ts
  projects/docs/src/app/docs-wrapper/pages/progressbar-page/progressbar-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textarea-page/textarea-page.component.ts
  projects/docs/src/assets/components-list.json
  projects/docs/src/styles/styles.scss
  projects/docs/src/styles/variables.scss
  projects/ng-components/lib/checkBox/checkBox.component.ts
  projects/ng-components/lib/datepicker/datepicker.component.ts
  projects/ng-components/lib/loader/loader.component.scss
  projects/ng-components/lib/modal/animation.ts
  projects/ng-components/lib/notification/notification.component.html
  projects/ng-components/lib/notification/notification.component.scss
  projects/ng-components/lib/notification/notification.component.ts
  projects/ng-components/lib/rating/rating.component.ts
  projects/ng-components/lib/slider/slider.component.ts
  projects/ng-components/lib/stepper/stepper.component.ts
  projects/ng-components/lib/tabs/tabs.component.ts
  projects/ng-components/lib/textarea/textarea.component.html
  projects/ng-components/lib/textarea/textarea.component.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.component.ts
  projects/ng-components/lib/timeline/timeline.component.scss
  projects/ng-components/lib/toggle/toggle.component.ts
Labels: 📚 Documentation

#405 docs: copies index.html into 404.html page
  .github/workflows/build-check.yml
  .github/workflows/gh-pages.yml
  package-lock.json
  package.json
  projects/docs/src/404.html
  projects/docs/src/@types/highlightjs-langs.d.ts
  projects/docs/src/app/common/code-snippet/code-snippet.component.ts
  projects/docs/src/app/common/dynamic-form/dynamic-form.module.ts
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.html
  projects/docs/src/app/docs-wrapper/getting-started/getting-started.component.ts
  projects/docs/src/app/docs-wrapper/pages/accordion-page/accordion-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/button-page/button-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/button-page/button-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/datepicker-page/datepicker-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/loader-page/loader-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/notification-page/notification-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/pagination-page/pagination-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/progressbar-page/progressbar-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/radiogroup-page/radiogroup-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/rating-page/rating-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/stepper-page/stepper-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/tabs-page/tabs-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/timer-page/timer-page.component.html
  projects/docs/src/app/docs-wrapper/pages/timer-page/timer-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/timer-page/timer-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/toggle-page/toggle-page.component.html
  projects/docs/src/app/docs-wrapper/pages/toggle-page/toggle-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/toggle-page/toggle-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/video-page/video-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/video-page/video-page.module.ts
  projects/ng-components/lib/checkBox/index.ts
  projects/ng-components/lib/checkbox/checkbox.component.html
  projects/ng-components/lib/checkbox/checkbox.component.scss
  projects/ng-components/lib/checkbox/checkbox.component.spec.ts
  projects/ng-components/lib/checkbox/checkbox.component.ts
  projects/ng-components/lib/checkbox/checkbox.module.ts
  projects/ng-components/lib/checkbox/index.ts
  projects/ng-components/lib/checkbox/package.json
  projects/ng-components/lib/dropdown/dropdown.component.html
  projects/ng-components/lib/textarea/textarea.component.html
  projects/ng-components/lib/textboxGroup/textboxGroup.component.html
  projects/ng-components/lib/toggle/toggle.component.html
  projects/ng-components/lib/toggle/toggle.component.scss
  projects/ng-components/lib/toggle/toggle.component.ts
  projects/ng-components/public-api.ts
Labels: 📚 Documentation, 🚀 CI/CD

#412 Fix/side menu re-render
  projects/docs/src/app/app.module.ts
  projects/docs/src/app/docs-wrapper/docs-wrapper.module.ts
  projects/docs/src/app/docs-wrapper/docs-wrapper.routes.ts
  projects/docs/src/app/docs-wrapper/pages/accordion-page/accordion-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/breadcrumb-page/breadcrumb-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/button-page/button-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/chip-page/chip-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/datepicker-page/datepicker-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/loader-page/loader-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/notification-page/notification-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/pagination-page/pagination-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/progressbar-page/progressbar-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/radiogroup-page/radiogroup-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/rating-page/rating-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/slider-page/slider-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/stepper-page/stepper-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/tabs-page/tabs-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textarea-page/textarea-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/timeline-page/timeline-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/timer-page/timer-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/toggle-page/toggle-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/tooltip-page/tooltip-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/video-page/video-page.module.ts
Labels: 🚧 Refactor

#411 fix(parser): fix parser in firefox
  package-lock.json
  projects/docs/src/app/common/services/api-extract.service.ts
Labels: 🐛 Bug

#416 feat(collapse): new component collapse
  package.json
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.html
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.html
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.ts
  projects/docs/src/app/docs-wrapper/getting-started/getting-started.component.ts
  projects/docs/src/app/docs-wrapper/pages/collapse-page/collapse-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/collapse-page/collapse-page.module.ts
  projects/docs/src/assets/components-list.json
  projects/ng-components/lib/collapse/collapse.component.spec.ts
  projects/ng-components/lib/collapse/collapse.component.ts
  projects/ng-components/lib/collapse/collapse.module.ts
  projects/ng-components/lib/collapse/index.ts
Labels: 🔨 Enhancement

#410 docs(textbox-group): adds controls
  projects/docs/src/app/common/dynamic-form/dynamic-form-item/dynamic-form-item.component.html
  projects/docs/src/app/common/dynamic-form/model/dynamicFormItem.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.module.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.component.html
  projects/ng-components/lib/textboxGroup/textboxGroup.component.ts
Labels: 🔨 Enhancement

#418 New beta release
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/todo.md
  package.json
  projects/docs/src/app/common/dynamic-form/dynamic-form-item/dynamic-form-item.component.html
  projects/docs/src/app/common/dynamic-form/dynamic-form-item/dynamic-form-item.component.ts
  projects/docs/src/app/common/dynamic-form/model/dynamicFormItem.ts
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.html
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.html
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.ts
  projects/docs/src/app/docs-wrapper/getting-started/getting-started.component.ts
  projects/docs/src/app/docs-wrapper/pages/breadcrumb-page/breadcrumb-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/collapse-page/collapse-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/collapse-page/collapse-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textarea-page/textarea-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.module.ts
  projects/docs/src/assets/components-list.json
  projects/ng-components/lib/accordion/accordion.module.ts
  projects/ng-components/lib/accordion/accordion.pipe.ts
  projects/ng-components/lib/accordion/index.ts
  projects/ng-components/lib/breadcrumb/breadcrumb.module.ts
  projects/ng-components/lib/breadcrumb/breadcrumb.pipe.ts
  projects/ng-components/lib/breadcrumb/index.ts
  projects/ng-components/lib/button/index.ts
  projects/ng-components/lib/collapse/collapse.component.spec.ts
  projects/ng-components/lib/collapse/collapse.component.ts
  projects/ng-components/lib/collapse/collapse.module.ts
  projects/ng-components/lib/collapse/index.ts
  projects/ng-components/lib/loader/index.ts
  projects/ng-components/lib/modal/index.ts
  projects/ng-components/lib/progressbar/index.ts
  projects/ng-components/lib/rating/index.ts
  projects/ng-components/lib/slider/index.ts
  projects/ng-components/lib/table/index.ts
  projects/ng-components/lib/table/table.module.ts
  projects/ng-components/lib/table/table.pipe.ts
  projects/ng-components/lib/textarea/textarea.component.html
  projects/ng-components/lib/textboxGroup/index.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.component.html
  projects/ng-components/lib/textboxGroup/textboxGroup.component.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.module.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.pipe.ts
  projects/ng-components/lib/tooltip/index.ts
  projects/ng-components/lib/tooltip/tooltip.module.ts
Labels: 🚀 Release

#425 HOTFIX: fix(table): fixes typescript definitions not being exported
  projects/ng-components/lib/table/index.ts
Labels: ❕ High Priority

#426 beta --> develop
  projects/ng-components/lib/table/index.ts
Labels: ❕ High Priority

#427 Added a component count badge in the side menu
  projects/docs/src/app/common/side-menu/side-menu.component.html
Labels: 📚 Documentation

#433 New beta release
  README.md
  package-lock.json
  package.json
  projects/docs/src/app/common/side-menu/side-menu.component.html
  projects/docs/src/app/docs-wrapper/getting-started/getting-started.component.ts
  projects/ng-components/README.md
Labels: 🚀 Release

#432 Feat/mobile support
  projects/docs/src/@types/contributor.d.ts
  projects/docs/src/@types/index.d.ts
  projects/docs/src/app/common/footer/footer.component.scss
  projects/docs/src/app/common/footer/footer.component.ts
  projects/docs/src/app/common/navbar/navbar.component.html
  projects/docs/src/app/common/navbar/navbar.component.scss
  projects/docs/src/app/common/navbar/navbar.component.ts
  projects/docs/src/app/common/navbar/navbar.module.ts
  projects/docs/src/app/common/not-found/not-found.component.ts
  projects/docs/src/app/common/side-menu/side-menu.component.html
  projects/docs/src/app/common/side-menu/side-menu.component.scss
  projects/docs/src/app/common/side-menu/side-menu.component.ts
  projects/docs/src/app/common/side-menu/side-menu.module.ts
  projects/docs/src/app/common/tech-stack/tech-stack.component.html
  projects/docs/src/app/docs-wrapper/docs-wrapper.component.scss
  projects/docs/src/app/home/home.component.html
  projects/docs/src/app/home/home.component.scss
  projects/docs/src/app/home/home.component.ts
  projects/docs/src/app/services/breakpoint.service.ts
  projects/docs/src/assets/images/404.svg
  projects/docs/src/assets/images/angular.png
  projects/docs/src/assets/images/boonying-profile.png
  projects/docs/src/assets/images/bootstrap.png
  projects/docs/src/assets/images/typescript.png
  projects/docs/src/styles/styles.scss
  projects/docs/tsconfig.app.json
  projects/ng-components/lib/collapse/collapse.component.ts
Labels: 🔨 Feature

#437 Feat/mobile ui MERGE #432 before this
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.scss
  projects/docs/src/app/docs-wrapper/pages/accordion-page/accordion-page.component.html
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.html
  projects/docs/src/app/docs-wrapper/pages/textlabel-page/textlabel-page.component.html
  projects/docs/src/app/docs-wrapper/pages/toggle-page/toggle-page.component.html
  projects/docs/src/app/docs-wrapper/pages/tooltip-page/tooltip-page.component.html
  projects/docs/src/app/docs-wrapper/pages/video-page/video-page.component.html
Labels: ⏳ Awaiting enabler, 🐛 Bug

#438 Fix/modal class name
  package-lock.json
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.html
  projects/ng-components/lib/accordion/accordion.component.spec.ts
  projects/ng-components/lib/breadcrumb/breadcrumb.component.spec.ts
  projects/ng-components/lib/modal/modal.component.html
  projects/ng-components/lib/modal/modal.component.spec.ts
  projects/ng-components/lib/modal/modal.component.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.component.spec.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.pipe.spec.ts
Labels: 🐛 Bug

#451 Refactor/modal
  .vscode/settings.json
  angular.json
  package.json
  projects/docs/src/@types/hljs.d.ts
  projects/docs/src/app/app.module.ts
  projects/docs/src/app/common/code-snippet/code-snippet.component.scss
  projects/docs/src/app/common/code-snippet/code-snippet.component.ts
  projects/docs/src/app/common/code-snippet/code-snippet.module.ts
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.html
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.scss
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.module.ts
  projects/docs/src/app/docs-wrapper/doc-page/notes/notes.component.scss
  projects/docs/src/app/docs-wrapper/doc-page/notes/notes.component.ts
  projects/docs/src/app/docs-wrapper/pages/accordion-page/accordion-page.component.html
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.html
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.html
  projects/docs/src/app/docs-wrapper/pages/modal-page/modal-page.component.ts
  projects/docs/src/utils/loadHighlightjs.ts
  projects/ng-components/karma.conf.js
  projects/ng-components/lib/accordion/accordion.pipe.ts
  projects/ng-components/lib/modal/animation.ts
  projects/ng-components/lib/modal/index.ts
  projects/ng-components/lib/modal/modal.backdrop.ts
  projects/ng-components/lib/modal/modal.component.html
  projects/ng-components/lib/modal/modal.component.scss
  projects/ng-components/lib/modal/modal.component.spec.ts
  projects/ng-components/lib/modal/modal.component.ts
  projects/ng-components/lib/modal/modal.module.ts
  projects/ng-components/lib/modal/modal.service.ts
  projects/ng-components/lib/modal/modal.type.ts
  tslint.json
Labels: 🚧 Refactor
