Repository seb-oss/ng-components, pull requests merged in 2020-08, with the labels that each got.

#453 docs(docs): add safe html pipe to apis
  projects/docs/src/app/common/pipes/safe-html.pipe.ts
  projects/docs/src/app/docs-wrapper/doc-page/apis/apis.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.module.ts
Labels: 📚 Documentation

#454 Security/fix anchor tags vulnerabilities
  package-lock.json
  package.json
  projects/docs/src/app/common/footer/footer.component.ts
  projects/docs/src/app/common/navbar/navbar.component.html
  projects/docs/src/app/common/side-menu/side-menu.component.html
  projects/docs/src/app/common/tech-stack/tech-stack.component.html
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.html
  projects/docs/src/app/home/home.component.html
Labels: 👮‍♂️ Security, 📦 Dependencies

#462 fix(radio-group): fixes focusing and custom template bugs
  projects/docs/src/app/docs-wrapper/pages/radiogroup-page/radiogroup-page.component.ts
  projects/ng-components/lib/radio-group/index.ts
  projects/ng-components/lib/radio-group/radio-group-safe.pipe.ts
  projects/ng-components/lib/radio-group/radio-group.component.html
  projects/ng-components/lib/radio-group/radio-group.component.ts
  projects/ng-components/lib/radio-group/radio-group.module.ts
Labels: 🐛 Bug

#464 Update textboxGroup.component.html
  projects/ng-components/lib/textboxGroup/textboxGroup.component.html
Labels: 🐛 Bug

#465 New release: Bug fixes
  package-lock.json
  package.json
  projects/docs/src/app/common/footer/footer.component.ts
  projects/docs/src/app/common/navbar/navbar.component.html
  projects/docs/src/app/common/pipes/safe-html.pipe.ts
  projects/docs/src/app/common/side-menu/side-menu.component.html
  projects/docs/src/app/common/tech-stack/tech-stack.component.html
  projects/docs/src/app/docs-wrapper/doc-page/apis/apis.component.ts
  projects/docs/src/app/docs-wrapper/doc-page/doc-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/checkbox-page/checkbox-page.component.html
  projects/docs/src/app/docs-wrapper/pages/radiogroup-page/radiogroup-page.component.ts
  projects/docs/src/app/home/home.component.html
  projects/ng-components/lib/dropdown/dropdown.component.ts
  projects/ng-components/lib/radio-group/index.ts
  projects/ng-components/lib/radio-group/radio-group-safe.pipe.ts
  projects/ng-components/lib/radio-group/radio-group.component.html
  projects/ng-components/lib/radio-group/radio-group.component.ts
  projects/ng-components/lib/radio-group/radio-group.module.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.component.html
Labels: 🚀 Release

#468 feat(dropdown): add shorthand to dropdown items
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.html
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.ts
  projects/ng-components/lib/dropdown/dropdown.component.ts
Labels: 🔨 Feature

#469 Minor release
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.html
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.ts
  projects/ng-components/lib/dropdown/dropdown.component.ts
Labels: 🚀 Release

#471 Update dropdown.component.html
  projects/ng-components/lib/dropdown/dropdown.component.html
Labels: 🐛 Bug

#472 minor release
  package-lock.json
  package.json
  projects/ng-components/lib/dropdown/dropdown.component.html
Labels: 🐛 Bug

#473 fix(dropdown): added shorthand to dropdown item
  projects/ng-components/lib/dropdown/dropdown.component.ts
Labels: 🚀 Release

#485 Disables the body scrolling when the modal is toggled on
  projects/ng-components/lib/modal/modal.component.spec.ts
  projects/ng-components/lib/modal/modal.component.ts
Labels: 🔨 Feature

#486 build(dep): update scully
  .scully/settings.yml
  package-lock.json
  package.json
Labels: 📦 Dependencies

#487 New release: bug fixes and improvements
  .scully/settings.yml
  package-lock.json
  package.json
  projects/ng-components/lib/collapse/package.json
  projects/ng-components/lib/dropdown/dropdown.component.html
  projects/ng-components/lib/modal/modal.component.spec.ts
  projects/ng-components/lib/modal/modal.component.ts
Labels: 🚀 Release

#478 table service improvements and docs update
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.scss
  projects/docs/src/app/docs-wrapper/pages/table-page/my-table-notes-example.component.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/notes-snippets.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.component.html
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/table-page/table-page.module.ts
  projects/docs/src/utils/loadHighlightjs.ts
  projects/ng-components/lib/table/table-body/table-body.component.html
  projects/ng-components/lib/table/table-header/table-header.component.html
  projects/ng-components/lib/table/table-td/table-td.component.html
  projects/ng-components/lib/table/table-th/table-th.component.html
  projects/ng-components/lib/table/table-th/table-th.component.ts
  projects/ng-components/lib/table/table.component.html
  projects/ng-components/lib/table/table.component.scss
  projects/ng-components/lib/table/table.component.spec.ts
  projects/ng-components/lib/table/table.component.ts
  projects/ng-components/lib/table/table.models.ts
  projects/ng-components/lib/table/table.service.spec.ts
  projects/ng-components/lib/table/table.service.ts
Labels: 📚 Documentation, 🔨 Feature

#496 refactor(textboxgroup): rename textboxgroup to textbox
  projects/docs/src/app/common/dynamic-form/dynamic-form-item/dynamic-form-item.component.html
  projects/docs/src/app/common/dynamic-form/dynamic-form.module.ts
  projects/docs/src/app/common/side-menu/side-menu.component.html
  projects/docs/src/app/common/side-menu/side-menu.component.scss
  projects/docs/src/app/common/side-menu/side-menu.component.ts
  projects/docs/src/app/common/side-menu/side-menu.module.ts
  projects/docs/src/app/docs-wrapper/docs-wrapper-routing.module.ts
  projects/docs/src/app/docs-wrapper/pages/textbox-page/textbox-page-routing.module.ts
  projects/docs/src/app/docs-wrapper/pages/textbox-page/textbox-page.component.ts
  projects/docs/src/app/docs-wrapper/pages/textbox-page/textbox-page.module.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page-routing.module.ts
  projects/docs/src/app/docs-wrapper/pages/textboxgroup-page/textboxgroup-page.module.ts
  projects/docs/src/assets/components-list.json
  projects/docs/src/assets/scully-routes.json
  projects/ng-components/lib/accordion/accordion.component.spec.ts
  projects/ng-components/lib/textbox/index.ts
  projects/ng-components/lib/textbox/package.json
  projects/ng-components/lib/textbox/textbox.component.html
  projects/ng-components/lib/textbox/textbox.component.scss
  projects/ng-components/lib/textbox/textbox.component.spec.ts
  projects/ng-components/lib/textbox/textbox.component.ts
  projects/ng-components/lib/textbox/textbox.module.ts
  projects/ng-components/lib/textbox/textbox.pipe.spec.ts
  projects/ng-components/lib/textbox/textboxSafeHtml.pipe.ts
  projects/ng-components/lib/textboxGroup/index.ts
  projects/ng-components/lib/textboxGroup/textboxGroup.module.ts
  projects/ng-components/public-api.ts
Labels: 🐛 Bug, 🚧 Refactor

#504 fix(dropdown): add placeholders
  projects/docs/src/app/docs-wrapper/doc-page/playground/playground.component.scss
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.html
  projects/docs/src/app/docs-wrapper/pages/dropdown-page/dropdown-page.component.ts
  projects/ng-components/lib/dropdown/dropdown.component.html
  projects/ng-components/lib/dropdown/dropdown.component.spec.ts
  projects/ng-components/lib/dropdown/dropdown.component.ts
Labels: 🐛 Bug
