Repository seb-oss/ng-components, pull requests merged in 2020-04, with the labels that each got.

#166 Feature/angular 9
  angular.json
  lib/src/dropdown/dropdown.component.spec.ts
  lib/src/dropdown/dropdown.component.ts
  lib/src/dropdown/index.ts
  lib/src/modal/public_api.ts
  lib/src/wizard/public_api.ts
  lib/src/wizard/wizard-step.component.ts
  lib/tsconfig.lib.json
  lib/tsconfig.lib.prod.json
  package-lock.json
  package.json
  projects/ng-components-docs/tsconfig.app.json
  src/tsconfig.app.json
Labels: dependencies, enhancement

#171 build(project): bumps all deps
  package-lock.json
  package.json
Labels: dependencies, enhancement

#184 build(upgrading-deps): upgrading dependencies
  lib/src/test.ts
  package-lock.json
  package.json
Labels: dependencies

#172 Feature pagination
  lib/src/pagination/index.ts
  lib/src/pagination/pagination.component.html
  lib/src/pagination/pagination.component.scss
  lib/src/pagination/pagination.component.spec.ts
  lib/src/pagination/pagination.component.ts
  lib/src/pagination/pagination.module.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/pagination/examples/pagination/pagination.component.html
  projects/ng-components-docs/src/app/examples/components/pagination/examples/pagination/pagination.component.ts
  projects/ng-components-docs/src/app/examples/components/pagination/pagination.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: enhancement
