Repository seb-oss/ng-components, pull requests merged in 2020-06, with the labels that each got.

#266 feat(accordion): new accordion component
  lib/src/accordion/accordion-style.pipe.ts
  lib/src/accordion/accordion.component.html
  lib/src/accordion/accordion.component.scss
  lib/src/accordion/accordion.component.spec.ts
  lib/src/accordion/accordion.component.ts
  lib/src/accordion/accordion.module.ts
  lib/src/accordion/accordion.pipe.ts
  lib/src/accordion/index.ts
  package-lock.json
  package.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/accordion/accordion.component.html
  projects/ng-components-docs/src/app/examples/components/accordion/accordion.component.ts
  projects/ng-components-docs/src/app/examples/components/accordion/accordion.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: enhancement

#298 fix(fix-apis): fix apis references
  lib/src/tabs/tabs.component.spec.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/components/example-page/api-list/api-list.component.ts
  projects/ng-components-docs/src/app/examples/components/accordion/accordion.module.ts
  projects/ng-components-docs/src/app/examples/components/breadcrumb/breadcrumb.module.ts
  projects/ng-components-docs/src/app/examples/components/buttons/buttons.module.ts
  projects/ng-components-docs/src/app/examples/components/chip/chip.module.ts
  projects/ng-components-docs/src/app/examples/components/dropdown/dropdown.module.ts
  projects/ng-components-docs/src/app/examples/components/modal/modal.module.ts
  projects/ng-components-docs/src/app/examples/components/pagination/pagination.module.ts
  projects/ng-components-docs/src/app/examples/components/radio-group/radio-group.module.ts
  projects/ng-components-docs/src/app/examples/components/tabs/examples/tabs/tabs.component.ts
  projects/ng-components-docs/src/app/examples/components/tabs/tabs.module.ts
  projects/ng-components-docs/src/app/examples/components/textArea/textArea.module.ts
  projects/ng-components-docs/src/app/examples/components/textLabels/text-labels.module.ts
  projects/ng-components-docs/src/app/examples/components/textboxGroup/textboxGroup.module.ts
  projects/ng-components-docs/src/app/examples/components/toggle/toggle.module.ts
  projects/ng-components-docs/src/app/examples/components/wizard/wizard.module.ts
  projects/ng-components-docs/src/app/utils/arrayFunctions.ts
Labels: bug

#284 feat(video): a new video component
  angular.json
  lib/src/public_api.ts
  lib/src/video/index.ts
  lib/src/video/video.component.html
  lib/src/video/video.component.scss
  lib/src/video/video.component.spec.ts
  lib/src/video/video.component.ts
  lib/src/video/video.module.ts
  package-lock.json
  package.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/video/video.component.html
  projects/ng-components-docs/src/app/examples/components/video/video.component.ts
  projects/ng-components-docs/src/app/examples/components/video/video.module.ts
  projects/ng-components-docs/src/assets/videos/sample.mp4
  webpack.config.js
Labels: enhancement

#315 fix(documentation): fixes some titles and imports for api and code
  projects/ng-components-docs/src/app/examples/components/accordion/accordion.module.ts
  projects/ng-components-docs/src/app/examples/components/chip/chip.module.ts
  projects/ng-components-docs/src/app/examples/components/dropdown/dropdown.module.ts
  projects/ng-components-docs/src/app/examples/components/modal/modal.module.ts
  projects/ng-components-docs/src/app/examples/components/pagination/pagination.module.ts
  projects/ng-components-docs/src/app/examples/components/radio-group/radio-group.module.ts
  projects/ng-components-docs/src/app/examples/components/tabs/tabs.module.ts
  projects/ng-components-docs/src/app/examples/components/textArea/textArea.module.ts
  projects/ng-components-docs/src/app/examples/components/textboxGroup/textboxGroup.module.ts
  projects/ng-components-docs/src/app/examples/components/toggle/toggle.module.ts
  projects/ng-components-docs/src/app/examples/components/video/video.module.ts
Labels: bug

#256 Feature/modal
  lib/src/modal/animation.ts
  lib/src/modal/index.ts
  lib/src/modal/modal.backdrop.ts
  lib/src/modal/modal.component.html
  lib/src/modal/modal.component.scss
  lib/src/modal/modal.component.spec.ts
  lib/src/modal/modal.component.ts
  lib/src/modal/modal.config.ts
  lib/src/modal/modal.directives.ts
  lib/src/modal/modal.html
  lib/src/modal/modal.injector.ts
  lib/src/modal/modal.module.ts
  lib/src/modal/modal.ref.ts
  lib/src/modal/modal.service.ts
  lib/src/modal/modal.ts
  lib/src/modal/modal.type.ts
  lib/src/modal/public_api.ts
  lib/src/modal/readme.md
  package-lock.json
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/buttons/buttons.module.ts
  projects/ng-components-docs/src/app/examples/components/modal/examples/modal/modal.component.html
  projects/ng-components-docs/src/app/examples/components/modal/examples/modal/modal.component.scss
  projects/ng-components-docs/src/app/examples/components/modal/examples/modal/modal.component.spec.ts
  projects/ng-components-docs/src/app/examples/components/modal/examples/modal/modal.component.ts
  projects/ng-components-docs/src/app/examples/components/modals/modals.component.html
  projects/ng-components-docs/src/app/examples/components/modals/modals.component.scss
  projects/ng-components-docs/src/app/examples/components/modals/modals.component.ts
  projects/ng-components-docs/src/app/examples/components/modals/modals.module.ts
  projects/ng-components-docs/src/app/examples/components/wizard/examples/wizard-forms/wizard-forms.component.ts
  projects/ng-components-docs/src/app/examples/components/wizard/examples/wizard/wizard.component.html
  projects/ng-components-docs/src/app/examples/components/wizard/examples/wizard/wizard.component.ts
  projects/ng-components-docs/src/app/examples/components/wizard/wizard.module.ts
  projects/ng-components-docs/src/app/examples/examples.module.ts
Labels: 🔨 Enhancement

#291 feat(rating): move rating component from angularComp to ng-comp
  lib/src/rating/index.ts
  lib/src/rating/rating.component.html
  lib/src/rating/rating.component.scss
  lib/src/rating/rating.component.spec.ts
  lib/src/rating/rating.component.ts
  lib/src/rating/rating.module.ts
  lib/src/rating/readme.md
  lib/src/rating/svgStar.svg.html
  lib/src/rating/svgStar.ts
  lib/src/rating/svgStarHollow.svg.html
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/components/menu/side-menu.component.scss
  projects/ng-components-docs/src/app/examples/components/rating/rating.component.html
  projects/ng-components-docs/src/app/examples/components/rating/rating.component.ts
  projects/ng-components-docs/src/app/examples/components/rating/rating.module.ts
Labels: 🔨 Enhancement

#289 Progress bar
  lib/src/progressBar/index.ts
  lib/src/progressBar/progressBar.component.html
  lib/src/progressBar/progressBar.component.spec.ts
  lib/src/progressBar/progressBar.component.ts
  lib/src/progressBar/progressBar.module.ts
  lib/src/progressBar/progressTheme.pipe.ts
  lib/src/public_api.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/progressBar/progressBar.component.html
  projects/ng-components-docs/src/app/examples/components/progressBar/progressBar.component.ts
  projects/ng-components-docs/src/app/examples/components/progressBar/progressBr.module.ts
Labels: 🔨 Enhancement

#297 feat(timeline): new timeline component
  lib/src/timeline/index.ts
  lib/src/timeline/timeline.component.html
  lib/src/timeline/timeline.component.scss
  lib/src/timeline/timeline.component.spec.ts
  lib/src/timeline/timeline.component.ts
  lib/src/timeline/timeline.module.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/timeline/timeline.component.html
  projects/ng-components-docs/src/app/examples/components/timeline/timeline.component.ts
  projects/ng-components-docs/src/app/examples/components/timeline/timeline.module.ts
Labels: 🔨 Enhancement

#311 Feature/slider
  .vscode/settings.json
  lib/src/slider/index.ts
  lib/src/slider/slider.component.html
  lib/src/slider/slider.component.scss
  lib/src/slider/slider.component.spec.ts
  lib/src/slider/slider.component.ts
  lib/src/slider/slider.module.ts
  lib/src/slider/slider.pipes.ts
  lib/src/slider/sliderUpDown.component.ts
  projects/ng-components-docs/src/app/app-routing.module.ts
  projects/ng-components-docs/src/app/examples/components/slider/slider.component.html
  projects/ng-components-docs/src/app/examples/components/slider/slider.component.scss
  projects/ng-components-docs/src/app/examples/components/slider/slider.component.ts
  projects/ng-components-docs/src/app/examples/components/slider/slider.module.ts
Labels: 🔨 Enhancement

#317 fix: Regex issues related to firefox and edge
  projects/ng-components-docs/src/app/components/example-page/api-list/api-list.component.ts
Labels: 🐛 Bug
